spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        hbm2ddl.import_files: sql/schema.sql
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        temp:
          use_jdbc_metadata_defaults: false
---
spring:
  profiles: dev
  datasource:
    username: postgres
    password: root
    schema: classpath:sql/test-schema.sql
    data: classpath:sql/test-data.sql
    url: jdbc:postgresql://localhost:5432/finances
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
---
spring:
  profiles: prod
  datasource:
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    url: postgres://u9vdiri9d3vc1:pb8a58f6fbcecc93f715ff93c74236cae0e481f7909e24fcc2377b8a08276d7a9@ceu9lmqblp8t3q.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d9ebum9hpth6ei

