DROP TABLE IF EXISTS authorities CASCADE;
DROP TABLE IF EXISTS group_authorities CASCADE;
DROP TABLE IF EXISTS group_members CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS persistent_logins CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS profile_categories CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS profile CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;

CREATE TABLE IF NOT EXISTS app_user
(
    username VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    enabled  BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS authorities
(
    username  VARCHAR(255) NOT NULL,
    authority VARCHAR(255) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES app_user (username)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_auth_username ON authorities (USERNAME, AUTHORITY);

CREATE TABLE IF NOT EXISTS groups
(
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS group_authorities
(
    group_id  BIGINT      NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_group_authorities_group FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE IF NOT EXISTS group_members
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    group_id INT         NOT NULL,
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE IF NOT EXISTS persistent_logins
(
    username  VARCHAR(64) NOT NULL,
    series    VARCHAR(64) PRIMARY KEY,
    token     VARCHAR(64) NOT NULL,
    last_used TIMESTAMP   NOT NULL
);

create table IF NOT EXISTS public.category
(
    id       bigserial primary key,
    name     varchar(255) not null,
    priority bigint       not null
);

create table IF NOT EXISTS public.payment
(
    id          bigserial primary key,
    amount      numeric(19, 2) not null,
    date_time   timestamp      not null,
    name        varchar(255),
    category_id bigint         not null
        constraint fka1ene89e5u89jwr887ge1b4a9
            references public.category,
    user_id     varchar         not null
        constraint fkjs1fo45o9f0ld1sgn2023tgy7
            references app_user
);

create table IF NOT EXISTS public.profile
(
    id      bigserial primary key,
    user_id varchar
        constraint fkrj2ycn1gq2m8533014hl2kv0t
            references app_user
);

create table IF NOT EXISTS public.profile_categories
(
    profile_id    bigint not null
        constraint fkevux5fmpfi0xglgrf9j7u2c4m
            references public.profile,
    categories_id bigint not null
        constraint uk_7ddr6dfgt0tmifdxq5e4gfko6
            unique
        constraint fkism980315ek9url6hu9abpf11
            references public.category
);